load("@rules_zig//zig:defs.bzl", "zig_library", "zig_test")

filegroup(
    name = "boundary_files",
    srcs = glob(["*.zig"]) + ["BUILD.bazel"],
    visibility = ["//pjrtx/tests/architecture:__pkg__"],
)

zig_library(
    name = "plugin",
    import_name = "pjrtx/plugin",
    main = "plugin.zig",
    visibility = ["//visibility:public"],
    deps = [
        "//pjrtx/compiler",
        "//pjrtx/core",
        "//pjrtx/runtime",
    ],
)

zig_test(
    name = "unit_tests",
    deps = [":plugin"],
)
