load("@rules_zig//zig:defs.bzl", "zig_library", "zig_test")

zig_library(
    name = "synthetic",
    import_name = "src/backend/synthetic",
    main = "backend.zig",
    visibility = ["//visibility:public"],
    deps = [
        "//src/backend",
        "//src/core",
    ],
)

zig_test(
    name = "synthetic_test",
    deps = [":synthetic"],
)
