load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_zig//zig:defs.bzl", "zig_library", "zig_test")

filegroup(
    name = "sources",
    srcs = [
        "BUILD.bazel",
        "compiler.zig",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "mlir_c_api",
    srcs = ["mlir_register.cc"],
    hdrs = ["mlir_c_api.h"],
    deps = [
        "@llvm-project//mlir:CAPIIR",
        "@llvm-project//mlir:CAPIShape",
        "@llvm-project//mlir:CAPITransforms",
        "@llvm-project//mlir:FuncExtensions",
        "@llvm-project//mlir:FuncDialect",
        "@llvm-project//mlir:ShapeDialect",
        "@shardy//shardy/integrations/c:sdy_capi",
        "@stablehlo//:chlo_capi",
        "@stablehlo//:stablehlo_capi",
        "@stablehlo//:stablehlo_dialect_capi",
    ],
)

zig_library(
    name = "compiler",
    import_name = "src/compiler",
    main = "compiler.zig",
    visibility = ["//visibility:public"],
    deps = [
        ":mlir_c_api",
        "//src/core",
    ],
)

zig_test(
    name = "compiler_test",
    deps = [":compiler"],
)
