/// Operation tag for binary elementwise instructions.
pub const ElementwiseBinaryOp = enum {
    add,
    subtract,
    multiply,
    divide,
    maximum,
    minimum,
    power,
    atan2,
    remainder,
    and_,
    or_,
    xor,
    shift_left,
    shift_right_arithmetic,
    shift_right_logical,
};

/// Operation tag for unary elementwise instructions.
pub const ElementwiseUnaryOp = enum {
    negate,
    exp,
    expm1,
    tanh,
    sqrt,
    rsqrt,
    abs,
    cbrt,
    ceil,
    floor,
    log,
    log1p,
    logistic,
    sine,
    cosine,
    not_,
    sign,
    is_finite,
    round_nearest_afz,
    round_nearest_even,
    popcnt,
    count_leading_zeros,
};

/// Comparison direction for compare instructions and comparator regions.
pub const CompareOp = enum {
    eq,
    ne,
    ge,
    gt,
    le,
    lt,
};

/// Update behavior for scatter instructions and scatter-update regions.
pub const ScatterUpdateKind = enum {
    set,
    add,
};

/// Fast Fourier transform variant requested by an executable instruction.
pub const FftKind = enum {
    fft,
    ifft,
    rfft,
    irfft,
};

/// Random number distribution requested by RNG instructions.
pub const RngDistribution = enum {
    uniform,
    normal,
};

/// Matrix orientation requested by triangular solve instructions.
pub const TriangularSolveTranspose = enum {
    no_transpose,
    transpose,
    adjoint,
};

/// Shared operation kind used by top-level and region plan instructions.
pub const PlanInstructionKind = enum {
    constant,
    copy_arg0,
    add,
    subtract,
    multiply,
    divide,
    maximum,
    minimum,
    power,
    atan2,
    remainder,
    and_,
    or_,
    xor,
    shift_left,
    shift_right_arithmetic,
    shift_right_logical,
    negate,
    exp,
    expm1,
    tanh,
    sqrt,
    rsqrt,
    abs,
    cbrt,
    ceil,
    floor,
    log,
    log1p,
    logistic,
    sine,
    cosine,
    not_,
    sign,
    is_finite,
    round_nearest_afz,
    round_nearest_even,
    popcnt,
    count_leading_zeros,
    convert,
    bitcast_convert,
    reshape,
    transpose,
    broadcast_in_dim,
    slice,
    dynamic_slice,
    dynamic_update_slice,
    pad,
    reverse,
    concatenate,
    iota,
    gather,
    sort,
    top_k,
    dot_general,
    reduce_sum,
    reduce_max,
    reduce_min,
    reduce_and,
    reduce_or,
    reduce_window_sum,
    reduce_window_max,
    compare,
    select,
    clamp,
    cholesky,
    complex,
    convolution,
    custom_call,
    fft,
    get_tuple_element,
    imag,
    optimization_barrier,
    partition_id,
    real,
    reduce_precision,
    rng,
    rng_bit_generator,
    scatter,
    triangular_solve,
    tuple,
    while_,
    unsupported,
};
