load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_zig//zig:defs.bzl", "zig_library", "zig_test")

filegroup(
    name = "boundary_files",
    srcs = glob(["*.zig"]) + ["BUILD.bazel"],
    visibility = ["//next/pjrtx/architecture:__pkg__"],
)

cc_library(
    name = "mlir_c_api",
    srcs = ["mlir_register.cc"],
    hdrs = ["mlir_c_api.h"],
    include_prefix = "pjrtx/compiler",
    visibility = [
        "//next/pjrtx/compiler:__pkg__",
        "//next/pjrtx/compiler/mlir_state:__pkg__",
    ],
    deps = [
        "@llvm-project//mlir:CAPIIR",
        "@llvm-project//mlir:CAPIShape",
        "@llvm-project//mlir:CAPITransforms",
        "@llvm-project//mlir:FuncDialect",
        "@llvm-project//mlir:FuncExtensions",
        "@llvm-project//mlir:Pass",
        "@llvm-project//mlir:ShapeDialect",
        "@shardy//shardy/integrations/c:sdy_capi",
        "@stablehlo//:chlo_capi",
        "@stablehlo//:stablehlo_capi",
        "@stablehlo//:stablehlo_dialect_capi",
    ],
)

zig_library(
    name = "compiler",
    import_name = "pjrtx/compiler",
    main = "compiler.zig",
    visibility = ["//visibility:public"],
    deps = [
        ":mlir_c_api",
        "//next/pjrtx/compiler/mlir_state",
        "//next/pjrtx/compiler/facts",
        "//next/pjrtx/core",
        "//next/pjrtx/target",
    ],
)

zig_test(
    name = "unit_tests",
    deps = [":compiler"],
)
