const std = @import("std");

const ir = @import("src/compiler/ir");
const mlx_metal = @import("src/backend/mlx_metal");
const dense = @import("msl_dense_elementwise.zig");
const refs = @import("msl_artifact_refs.zig");

/// Writes the generated Metal source artifact for one executable program.
pub fn writeMsl(writer: *std.Io.Writer, plan: *const ir.ExecutablePlan, program: *const mlx_metal.Program) !void {
    try writer.writeAll(
        \\#include <metal_stdlib>
        \\using namespace metal;
        \\
        \\// Generated by PjRTx from compiler/runtime executable IR.
        \\// This file is an experimental metal-cpp backend artifact. It is not
        \\// used by the default MLX execution path unless a future env-selected
        \\// backend runner consumes it.
        \\
    );
    try writer.print("// values={d} instructions={d} schedule_items={d} nodes={d} fusion_groups={d}\n\n", .{
        plan.values.len,
        plan.instructions.len,
        program.schedule.len,
        program.nodes.len,
        program.fusion_groups.len,
    });

    if (dense.hasKernels(plan)) {
        try dense.writeSourceHelper(writer);
    }

    for (plan.instructions, 0..) |instruction, instruction_index| {
        try writer.print("// instruction {d}: {s}", .{ instruction_index, @tagName(instruction.kind) });
        try refs.writeValueRefList(writer, plan, " inputs", instruction.inputs);
        try refs.writeValueRefList(writer, plan, " outputs", instruction.outputs);
        try refs.writeInstructionAttributes(writer, instruction);
        try writer.writeByte('\n');

        if (dense.Kernel.init(plan, instruction, instruction_index)) |kernel| {
            try kernel.writeMsl(writer);
        } else switch (instruction.kind) {
            .dot_general => try writeDotKernelSkeleton(writer, instruction_index, instruction),
            else => {},
        }
    }
}

/// Writes the experimental MetalCPP host scaffold artifact.
pub fn writeMetalCppHost(writer: *std.Io.Writer, stem: []const u8, plan: *const ir.ExecutablePlan, program: *const mlx_metal.Program) !void {
    try writer.print(
        \\// Generated by PjRTx from compiler/runtime executable IR.
        \\// This is an experimental metal-cpp host scaffold for {s}.metal.
        \\#include <Metal/Metal.hpp>
        \\
        \\namespace pjrtx::metalcpp_generated {{
        \\
        \\struct ProgramShape {{
        \\  static constexpr unsigned values = {d};
        \\  static constexpr unsigned instructions = {d};
        \\  static constexpr unsigned schedule_items = {d};
        \\  static constexpr unsigned nodes = {d};
        \\  static constexpr unsigned fusion_groups = {d};
        \\}};
        \\
        \\}}  // namespace pjrtx::metalcpp_generated
        \\
    , .{
        stem,
        plan.values.len,
        plan.instructions.len,
        program.schedule.len,
        program.nodes.len,
        program.fusion_groups.len,
    });
}

fn writeDotKernelSkeleton(writer: *std.Io.Writer, instruction_index: usize, instruction: ir.PlanInstruction) !void {
    try writer.print(
        \\// dot_general lowering candidate {d}
        \\// lhs_contract=
    , .{instruction_index});
    try writeOptionalDims(writer, instruction.lhs_contracting_dimensions);
    try writer.writeAll(" rhs_contract=");
    try writeOptionalDims(writer, instruction.rhs_contracting_dimensions);
    try writer.writeByte('\n');
    try writer.print(
        \\kernel void pjrtx_i{d}_dot_general_placeholder(
        \\    device const float* lhs [[buffer(0)]],
        \\    device const float* rhs [[buffer(1)]],
        \\    device float* out [[buffer(2)]],
        \\    uint gid [[thread_position_in_grid]]) {{
        \\    // TODO: specialize tile sizes and memory layout from PjRTx IR.
        \\    out[gid] = 0.0f;
        \\}}
        \\
    , .{instruction_index});
}

fn writeOptionalDims(writer: *std.Io.Writer, dims: ?[]const i64) !void {
    const values = dims orelse {
        try writer.writeAll("[]");
        return;
    };
    try writer.writeByte('[');
    for (values, 0..) |value, index| {
        if (index != 0) try writer.writeAll(",");
        try writer.print("{d}", .{value});
    }
    try writer.writeByte(']');
}

